spring:
  application:
    name: http-exercise
  datasource:
    url: jdbc:mariadb://localhost:3306/httpexercise
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none # Flyway will manage schema changes
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mariadb://localhost:3306/httpexercise
    user: user
    password: password
    connectRetries: 10
    encoding: UTF-8
    baseline-on-migrate: true
security:
  jwt:
    secret: w4vjmZlJSat95OPwx1BCwLp6T3vNbhZJuH6EPZtbL+k=
    expiration-ms: 86400000
#server:
#  address: 0.0.0.0
#  port: 8080
